---
title: "The reticulate package"
subtitle: "Integration of Python into R projects"
output: html_notebook
---

***

### Setup

```{r setup}
library(reticulate)
# use_python("/usr/local/bin/python")
readr::write_csv(nycflights13::flights,path = "flights.csv")
```

***

# From Python to R


### Use Python to manipulate data

```{python}
import pandas
flights = pandas.read_csv("flights.csv")
flights = flights[flights['dest'] == "ORD"]
flights = flights[['carrier', 'dep_delay', 'arr_delay']]
flights = flights.dropna()
```

### Use R to visualize Pandas DataFrame

```{r, fig.width=7, fig.height=3}
library(ggplot2)
ggplot(py$flights, aes(carrier, arr_delay)) + geom_point() + geom_jitter()
```

***

# From R to Python

### Use R to read and manipulate data

```{r, message=FALSE}
library(tidyverse)
flights <- read_csv("flights.csv") %>%
  filter(dest == "ORD") %>%
  select(carrier, dep_delay, arr_delay) %>%
  na.omit()
```

### Use Python to print R dataframe

```{python}
print ( r . flights . head (10))
```

```{python}
import pandas
file_name = "http://samplecsvs.s3.amazonaws.com/SalesJan2009.csv"
df = pandas.read_csv(file_name)
print(df.head())
```

```{r}
ggplot(py$df) + geom_bar(aes(Payment_Type))
```

```{r}
library(dplyr)
grouped <- tibble(card = py$df$Payment_Type) %>% 
  group_by(card) %>% 
  summarize(total = n())
```


```{python}
print(r.grouped)
```



***

See the [reticulate website](https://rstudio.github.io/reticulate/index.html) for details.

